// src/workers/export/handler.ts

import archiver from 'archiver';
import { createWriteStream } from 'fs';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { db } from '@/lib/db/client';
import type { ExportJobData } from '@/types/queue';

// Storage provider would be imported here
// import { getStorageProvider } from '@/lib/providers/storage';

export interface ExportResult {
  fileKey: string;
  fileName: string;
  sizeBytes: number;
}

/**
 * Handle an export job — package outputs into a downloadable archive.
 */
export async function handleExportJob(data: ExportJobData): Promise<ExportResult> {
  const { jobId, userId, exportType, clipId } = data;
  const tempDir = path.join(os.tmpdir(), `export-${jobId}-${Date.now()}`);
  await fs.mkdir(tempDir, { recursive: true });

  try {
    switch (exportType) {
      case 'single_clip':
        return await exportSingleClip(jobId, clipId!, tempDir);
      case 'all_clips':
        return await exportAllClips(jobId, tempDir);
      case 'all_texts':
        return await exportAllTexts(jobId, tempDir);
      case 'full_package':
        return await exportFullPackage(jobId, tempDir);
      default:
        throw new Error(`Unknown export type: ${exportType}`);
    }
  } finally {
    await fs.rm(tempDir, { recursive: true, force: true }).catch(() => {});
  }
}

// --- SINGLE CLIP ---

async function exportSingleClip(
  jobId: string,
  clipId: string,
  tempDir: string,
): Promise<ExportResult> {
  const clip = await db.clip.findUniqueOrThrow({
    where: { id: clipId },
    select: { title: true, renderedFiles: true, socialCaption: true },
  });

  const renderedFiles = clip.renderedFiles as Record<string, string>;
  const primaryKey = renderedFiles['9x16'] ?? Object.values(renderedFiles)[0];

  if (!primaryKey) {
    throw new Error('No rendered file available for this clip');
  }

  // Download from storage to temp
  const fileName = sanitizeFilename(`${clip.title}.mp4`);
  const localPath = path.join(tempDir, fileName);

  // TODO: Download from storage provider
  // await storageProvider.download(primaryKey, localPath);

  // For now, return the storage key directly
  return {
    fileKey: primaryKey,
    fileName,
    sizeBytes: 0, // Would be actual file size
  };
}

// --- ALL CLIPS ---

async function exportAllClips(jobId: string, tempDir: string): Promise<ExportResult> {
  const clips = await db.clip.findMany({
    where: { jobId, status: 'APPROVED' },
    orderBy: { sortOrder: 'asc' },
    select: { id: true, title: true, renderedFiles: true, sortOrder: true },
  });

  if (clips.length === 0) {
    throw new Error('No approved clips to export');
  }

  const zipPath = path.join(tempDir, 'clips.zip');
  const archive = archiver('zip', { zlib: { level: 6 } });
  const output = createWriteStream(zipPath);

  return new Promise((resolve, reject) => {
    output.on('close', async () => {
      const stats = await fs.stat(zipPath);
      const fileKey = `exports/${jobId}/clips-${Date.now()}.zip`;

      // TODO: Upload to storage
      // await storageProvider.upload(zipPath, fileKey);

      resolve({
        fileKey,
        fileName: `clips-${clips.length}.zip`,
        sizeBytes: stats.size,
      });
    });

    archive.on('error', reject);
    archive.pipe(output);

    for (const clip of clips) {
      const rendered = clip.renderedFiles as Record<string, string>;
      const primaryKey = rendered['9x16'] ?? Object.values(rendered)[0];

      if (primaryKey) {
        const fileName = sanitizeFilename(
          `${String(clip.sortOrder + 1).padStart(2, '0')}-${clip.title}.mp4`,
        );
        // TODO: Stream from storage into archive
        // archive.append(storageProvider.createReadStream(primaryKey), { name: fileName });

        // Placeholder — in production, this streams from storage
        archive.append(`[video: ${primaryKey}]`, { name: fileName });
      }
    }

    archive.finalize();
  });
}

// --- ALL TEXTS ---

async function exportAllTexts(jobId: string, tempDir: string): Promise<ExportResult> {
  const job = await db.job.findUniqueOrThrow({
    where: { id: jobId },
    select: { sourceTitle: true },
  });

  const texts = await db.textOutput.findMany({
    where: { jobId },
    orderBy: { sortOrder: 'asc' },
    select: { type: true, label: true, content: true, wordCount: true, threadPosts: true },
  });

  const transcript = await db.transcript.findUnique({
    where: { jobId },
    select: { fullText: true },
  });

  // Build a single Markdown file with all text outputs
  let markdown = `# ${job.sourceTitle ?? 'Content'} — Text Outputs\n\n`;
  markdown += `*Generated by OriginClipAI*\n\n---\n\n`;

  for (const text of texts) {
    markdown += `## ${text.label}\n\n`;
    markdown += `*Type: ${text.type} · ${text.wordCount} words*\n\n`;

    if (text.type === 'X_THREAD' && text.threadPosts) {
      const posts = text.threadPosts as Array<{ postNumber: number; text: string }>;
      for (const post of posts) {
        markdown += `**${post.postNumber}/** ${post.text}\n\n`;
      }
    } else {
      markdown += `${text.content}\n\n`;
    }

    markdown += `---\n\n`;
  }

  if (transcript) {
    markdown += `## Full Transcript\n\n`;
    markdown += transcript.fullText;
  }

  const mdPath = path.join(tempDir, 损'text-outputs.md');
  await fs.writeFile(mdPath, markdown, 'utf-8');

  const stats = await fs.stat(mdPath);
  const fileKey = `exports/${jobId}/texts-${Date.now()}.md`;

  // TODO: Upload to storage
  // await storageProvider.upload(mdPath, fileKey);

  return {
    fileKey,
    fileName: 'text-outputs.md',
    sizeBytes: stats.size,
  };
}

// --- FULL PACKAGE ---

async function exportFullPackage(jobId: string, tempDir: string): Promise<ExportResult> {
  const job = await db.job.findUniqueOrThrow({
    where: { id: jobId },
    select: { sourceTitle: true },
  });

  const clips = await db.clip.findMany({
    where: { jobId, status: 'APPROVED' },
    orderBy: { sortOrder: 'asc' },
    select: {
      id: true, title: true, renderedFiles: true, sortOrder: true,
      socialCaption: true, hashtags: true, transcriptExcerpt: true,
    },
  });

  const texts = await db.textOutput.findMany({
    where: { jobId },
    orderBy: { sortOrder: 'asc' },
  });

  const transcript = await db.transcript.findUnique({
    where: { jobId },
    select: { fullText: true, speakers: true },
  });

  const zipPath = path.join(tempDir, 'full-package.zip');
  const archive = archiver('zip', { zlib: { level: 6 } });
  const output = createWriteStream(zipPath);

  return new Promise((resolve, reject) => {
    output.on('close', async () => {
      const stats = await fs.stat(zipPath);
      const fileKey = `exports/${jobId}/package-${Date.now()}.zip`;

      resolve({
        fileKey,
        fileName: `${sanitizeFilename(job.sourceTitle ?? 'export')}-package.zip`,
        sizeBytes: stats.size,
      });
    });

    archive.on('error', reject);
    archive.pipe(output);

    // 1. Clips folder
    for (const clip of clips) {
      const rendered = clip.renderedFiles as Record<string, string>;
      const primaryKey = rendered['9x16'] ?? Object.values(rendered)[0];

      if (primaryKey) {
        const fileName = sanitizeFilename(
          `${String(clip.sortOrder + 1).padStart(2, '0')}-${clip.title}.mp4`,
        );
        archive.append(`[video: ${primaryKey}]`, { name: `clips/${fileName}` });
      }

      // Clip metadata
      if (clip.socialCaption || clip.transcriptExcerpt) {
        const meta = [
          `# ${clip.title}`,
          '',
          clip.socialCaption ? `**Caption:** ${clip.socialCaption}` : '',
          clip.hashtags ? `**Hashtags:** ${(clip.hashtags as string[]).map(h => `#${h}`).join(' ')}` : '',
          '',
          clip.transcriptExcerpt ? `**Transcript:**\n${clip.transcriptExcerpt}` : '',
        ].filter(Boolean).join('\n');

        archive.append(meta, {
          name: `clips/${String(clip.sortOrder + 1).padStart(2, '0')}-${sanitizeFilename(clip.title)}.md`,
        });
      }
    }

    // 2. Text outputs
    let textMd = `# ${job.sourceTitle ?? 'Content'} — Text Outputs\n\n`;
    for (const text of texts) {
      textMd += `## ${text.label}\n\n${text.content}\n\n---\n\n`;
    }
    archive.append(textMd, { name: 'text-outputs.md' });

    // 3. Full transcript
    if (transcript?.fullText) {
      archive.append(transcript.fullText, { name: 'transcript.txt' });
    }

    // 4. README
    const readme = `# Export Package: ${job.sourceTitle ?? 'Content'}

Generated by OriginClipAI on ${new Date().toISOString().split('T')[0]}

## Contents

- \`clips/\` — ${clips.length} approved video clips (MP4) with metadata
- \`text-outputs.md\` — ${texts.length} text outputs (LinkedIn, X, newsletter, etc.)
- \`transcript.txt\` — Full transcript${transcript?.speakers ? ` (${(transcript.speakers as any[]).length} speakers)` : ''}

## Usage

Video clips are ready to upload to TikTok, YouTube Shorts, Instagram Reels, or any platform.
Text outputs are ready to copy-paste into LinkedIn, X, Substack, or your newsletter tool.
`;
    archive.append(readme, { name: 'README.md' });

    archive.finalize();
  });
}

// --- UTILS ---

function sanitizeFilename(name: string): string {
  return name
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 100);
}
